services:
  - type: web
    name: ieee-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: FRONTEND_URL
        value: "https://vaikaai.vercel.app"
      - key: GROQ_MODEL_NAME
        value: groq/compound
      - key: CATEGORICAL_MODEL
        value: openai/gpt-oss-20b
      - key: WATCHER_MODEL
        value: openai/gpt-oss-20b
      # The following keys have `sync: false` meaning you will securely
      # enter them in the Render Dashboard and they won't be exposed in code.
      - key: GROQ_API_KEY
        sync: false
      - key: CATEGORICAL_MODEL_API_KEY
        sync: false
      - key: WATCHER_MODEL_API_KEY
        sync: false
      - key: FIREBASE_CREDS_BASE64
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: FIREBASE_COLLECTION
        value: ieee-members
      - key: STUDENT_BRANCH_TOP_K
        value: "4"
      - key: STUDENT_BRANCH_MIN_SIMILARITY
        value: "0.35"
